version: 2.0

references:

  container_config: &container_config
    resource_class: medium
    docker:
      - image: menny/android_bazel:1.10.0

    working_directory: /opt/workspace/

  base_environment: &base_environment
    TERM: dumb

  setup_bazel_rc_for_ci: &setup_bazel_rc_for_ci
     name: Setup Circle CI bazelrc
     command: cp .circleci/ci.bazelrc ci.bazelrc

  cache_key_build: &cache_key_build
    key: navajo-{{ checksum "WORKSPACE" }}-{{ checksum "clients/android/resolved_main_dependencies.bzl"}}-{{ checksum ".bazelrc"}}

  cache_key_test: &cache_key_test
    key: navajo-test-{{ checksum "WORKSPACE" }}-{{ checksum "clients/android/resolved_main_dependencies.bzl"}}-{{ checksum ".bazelrc"}}

  cache_key_check: &cache_key_check
    key: navajo-check-{{ checksum "WORKSPACE" }}-{{ checksum "clients/android/resolved_main_dependencies.bzl"}}-{{ checksum ".bazelrc"}}

  cache_paths: &cache_paths
    paths:
      - "bazel-bin"
      - "bazel-genfiles"
      - "bazel-navajo-chat"
      - "bazel-out"
      - "bazel-testlogs"
      - "/opt/android-sdk-linux/licenses/"

jobs:

  build:
    <<: *container_config
    environment:
      <<: *base_environment
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key_build

      - run:
          <<: *setup_bazel_rc_for_ci

      - run:
          name: Build
          command: bazel build //...

      - store_artifacts:
          path: /opt/workspace/bazel-bin/clients/android/app/*.apk
          destination: apks/

      - save_cache:
          <<: *cache_key_build
          <<: *cache_paths
  test:
    <<: *container_config
    environment:
      <<: *base_environment
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key_test
      - run:
          <<: *setup_bazel_rc_for_ci

      - run:
          name: Build
          command: bazel test //...

      - store_artifacts:
          path: /opt/workspace/bazel-testlogs/**
          destination: testlogs/

      - save_cache:
          <<: *cache_key_test
          <<: *cache_paths

  check:
    <<: *container_config
    environment:
      <<: *base_environment
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key_check
      - run:
          <<: *setup_bazel_rc_for_ci

      - run:
          name: Run build with extra checks
          command: exit 0

      - store_artifacts:
          path: /opt/workspace/bazel-testlogs/**
          destination: testlogs/

      - save_cache:
          <<: *cache_key_check
          <<: *cache_paths

workflows:
  version: 2

  build_check_tests_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - check:
          requires:
            - build
